import { useEffect, useState } from 'react';
import { api, getApiError } from '../../lib/api';

interface QueueItem { trackingCode:string; studentName:string; fatherName:string; universityName:string; faculty:string; department:string; documentType:string; gpa:string; submittedAt:string; issuanceSystem:string; legacyMaktoubNumber?:string; }

export default function MinistryPortal() {
  const [queue,setQueue]=useState<QueueItem[]>([]); const [selected,setSelected]=useState<QueueItem|null>(null);
  const [remarks,setRemarks]=useState(''); const [message,setMessage]=useState<{error?:boolean;text:string}|null>(null); const [loading,setLoading]=useState(false);
  const load=async()=>{try{const {data}=await api.get<QueueItem[]>('/api/ministry/queue');setQueue(data);}catch(err){setMessage({error:true,text:getApiError(err,'Could not load the review queue.')});}};
  useEffect(()=>{let active=true;void api.get<QueueItem[]>('/api/ministry/queue').then(({data})=>{if(active)setQueue(data);}).catch(err=>{if(active)setMessage({error:true,text:getApiError(err,'Could not load the review queue.')});});return()=>{active=false;};},[]);
  const review=async(action:'verify'|'reject')=>{if(!selected)return;setLoading(true);setMessage(null);try{const {data}=await api.post('/api/ministry/review',{code:selected.trackingCode,action,remarks});setMessage({text:data.message});setSelected(null);setRemarks('');await load();requestAnimationFrame(()=>window.scrollTo({top:0,behavior:'smooth'}));}catch(err){setMessage({error:true,text:getApiError(err,'The decision could not be recorded.')});}finally{setLoading(false);}};
  return <section className="mx-auto max-w-7xl px-4 py-10 sm:px-6 lg:px-8"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="text-xs font-black uppercase tracking-[.22em] text-emerald-700">Ministry workspace</p><h1 className="mt-2 text-3xl font-black tracking-tight sm:text-4xl">Credential review queue</h1><p className="mt-2 text-slate-500">Audit and attest records submitted by accredited institutions.</p></div><div className="flex items-center gap-3 rounded-2xl border border-slate-200 bg-white px-5 py-3 shadow-sm"><span className="grid h-9 w-9 place-items-center rounded-xl bg-amber-100 font-black text-amber-800">{queue.length}</span><span className="text-sm font-bold text-slate-600">Awaiting review</span></div></div>
    {message&&<div className={`mt-6 rounded-xl border px-5 py-4 text-sm font-bold ${message.error?'border-red-200 bg-red-50 text-red-700':'border-emerald-200 bg-emerald-50 text-emerald-800'}`}>{message.text}</div>}
    <div className="mt-8 grid gap-6 lg:grid-cols-[1fr_390px]"><div className="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm"><div className="flex items-center justify-between border-b border-slate-100 px-6 py-5"><h2 className="font-black">Incoming records</h2><button onClick={()=>void load()} className="text-xs font-bold text-emerald-700">Refresh queue</button></div>{queue.length===0?<div className="px-6 py-20 text-center"><div className="mx-auto grid h-14 w-14 place-items-center rounded-2xl bg-emerald-100 text-2xl text-emerald-700">✓</div><h3 className="mt-4 font-black">Queue is clear</h3><p className="mt-1 text-sm text-slate-500">There are no credentials awaiting review.</p></div>:<div className="divide-y divide-slate-100">{queue.map(item=><button key={item.trackingCode} onClick={()=>{setSelected(item);setRemarks('');setMessage(null);}} className={`grid w-full gap-3 px-5 py-5 text-left transition hover:bg-emerald-50/50 sm:grid-cols-[1fr_1fr_120px] ${selected?.trackingCode===item.trackingCode?'bg-emerald-50 ring-1 ring-inset ring-emerald-200':''}`}><div><p className="font-black text-slate-900">{item.studentName}</p><p className="mt-1 text-xs text-slate-500">{item.faculty} · {item.department}</p></div><div><p className="text-sm font-bold text-slate-700">{item.universityName}</p><p className="mt-1 text-xs text-slate-400">{new Date(item.submittedAt).toLocaleDateString()}</p></div><code className="h-fit rounded-lg bg-slate-100 px-2 py-1 text-center text-xs font-black tracking-wider text-slate-700">{item.trackingCode}</code></button>)}</div>}</div>
      <aside className="h-fit rounded-3xl bg-slate-950 p-6 text-white shadow-xl lg:sticky lg:top-24">{!selected?<div className="py-16 text-center"><svg viewBox="0 0 24 24" className="mx-auto h-12 w-12 text-slate-600" fill="none" stroke="currentColor"><path d="M8 3h8l2 3v15H6V6l2-3Z"/><path d="M9 11h6M9 15h6"/></svg><p className="mt-4 font-bold text-slate-300">Select a record to begin the audit</p></div>:<><p className="text-xs font-black uppercase tracking-[.2em] text-emerald-300">Decision panel</p><h2 className="mt-3 text-2xl font-black">{selected.studentName}</h2><dl className="mt-6 space-y-4 text-sm">{[['Tracking code',selected.trackingCode],['Father’s name',selected.fatherName],['University',selected.universityName],['Faculty',selected.faculty],['Department',selected.department],['Document',selected.documentType],['GPA',selected.gpa],['Origin',selected.issuanceSystem],...(selected.legacyMaktoubNumber?[['Maktoub',selected.legacyMaktoubNumber]]:[])].map(([k,v])=><div key={k} className="flex justify-between gap-4 border-b border-white/10 pb-3"><dt className="text-slate-400">{k}</dt><dd className="text-right font-bold">{v}</dd></div>)}</dl><label className="mt-6 block text-xs font-bold uppercase tracking-wide text-slate-300">Official decision notes<textarea value={remarks} onChange={e=>setRemarks(e.target.value)} rows={4} className="mt-2 w-full resize-none rounded-xl border border-white/15 bg-white/10 p-3 text-sm font-normal normal-case tracking-normal text-white outline-none focus:border-emerald-400" placeholder="Record the basis for this decision…"/></label><div className="mt-5 grid grid-cols-3 gap-2"><button type="button" disabled={loading} onClick={()=>{setSelected(null);setRemarks('');}} className="rounded-xl border border-slate-500 bg-white/5 px-2 py-3 text-sm font-black text-slate-200 hover:bg-white/10">Cancel</button><button disabled={loading} onClick={()=>void review('reject')} className="rounded-xl border border-red-400/40 bg-red-500/10 px-2 py-3 text-sm font-black text-red-300 hover:bg-red-500/20">Reject</button><button disabled={loading} onClick={()=>void review('verify')} className="rounded-xl bg-emerald-400 px-2 py-3 text-sm font-black text-emerald-950 hover:bg-emerald-300">{loading?'Saving…':'Approve'}</button></div></>}</aside></div>
  </section>;
}
